import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(req: Request) {
  try {
    const { seriesId, trend, forecastSummary } = await req.json();

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ 
        reasoning: `AI Reasoning is currently in demo mode. The ${seriesId} forecast shows a ${trend} trend based on Prophet's historical decomposition. In a production environment, this text would be generated by Gemini 3 Flash to provide nuanced economic context.` 
      });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `You are a senior macroeconomic analyst. 
    Analyze the following forecast for ${seriesId}:
    - Identified Trend: ${trend}
    - Forecast Summary: ${JSON.stringify(forecastSummary)}
    
    Provide a 3-sentence economic reasoning for this trend. Be professional, concise, and insightful.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return NextResponse.json({ reasoning: text });
  } catch (e) {
    console.error("Gemini Error:", e);
    return NextResponse.json({ error: "Failed to generate reasoning" }, { status: 500 });
  }
}
